### PR TITLE
Fix #1034 & Deprecate VersionSpecific & update copyright

### LINKED ISSUE #1034: PAPI incompatible with future versions of Paper
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin Bug

### What happens?

PAPI tries to parse the relocated CraftBukkit package version, which is unsupported behavior. 

### Expected Behaviour

PAPI not explicitly parsing the relocation version in https://github.com/PlaceholderAPI/PlaceholderAPI/blob/master/src/main/java/me/clip/placeholderapi/PlaceholderAPIPlugin.java#L58

See https://forums.papermc.io/threads/paper-velocity-1-20-4.998/#post-2955

### How to Reproduce

Currently not possible, but this will be important in the future

### `/papi dump` Output

N/A

### Console Log

_No response_

### Errors

https://paste.helpch.at/egoxexuhim.rb

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by PiggyPiglet**
I don't code anymorethis was all @BlitzOffline i promise

### CODE REVIEW

File: src/main/java/me/clip/placeholderapi/expansion/VersionSpecific.java [hunk 1]
```diff
@@ -28,6 +28,7 @@
  *
  * @author Ryan McCarthy
  */
```
Comment (Andre601) [inline src/main/java/me/clip/placeholderapi/expansion/VersionSpecific.java:30]:
```suggestion
 * @author Ryan McCarthy
 *
 * @deprecated Will be removed in a future release.
 */
```

**Review by Andre601 — CHANGES_REQUESTED** [review]
Just a small thing to add for clarity

**Review by Andre601 — APPROVED** [review]

**Comment by Andre601** [comment]
Anything stopping this from a merge?

**Review by darbyjack — APPROVED** [review]
