### PR TITLE
fix for all expansions stop loading after an exception is thrown (#1094)

### LINKED ISSUE #1094: External expansions stop loading after an exception is thrown
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin Bug

### What happens?

When one expansion fails to load (for whatever reason) and throws an exception, all other expansions followed are not attempted to be loaded

### Expected Behaviour

All other expansions should still be loaded, with just the 1 expansion failing to load

### How to Reproduce

Generate an exception during the file operations when registering an external expansion

### `/papi dump` Output

N/A

### Console Log

_No response_

### Errors

_No response_

### Additional Info

This is because of this line [here](https://github.com/PlaceholderAPI/PlaceholderAPI/blob/545f7f0bbdf1e2179d194f831b09ee0a07562f47/src/main/java/me/clip/placeholderapi/expansion/manager/LocalExpansionManager.java#L434)

When the method is called and an exception occurs, the mapping operation is abandoned
```java
return Arrays.stream(files)
        .map(this::findExpansionInFile)
        .collect(Futures.collector());

### PR DESCRIPTION
**Pull request by Kqliber**
### Type

- [x] Internal change (Doesn't affect end-user).
- [ ] External change (Does affect end-user).
- [ ] Wiki (Changes towards the [Wiki]).
- [ ] Other: __________ 

### Description

Closes #1094

[Wiki]: https://wiki.placeholderapi.com

### CODE REVIEW

File: src/main/java/me/clip/placeholderapi/expansion/manager/LocalExpansionManager.java [hunk 1]
```diff
@@ -66,6 +67,8 @@
 import org.jetbrains.annotations.Nullable;
 import org.jetbrains.annotations.Unmodifiable;
 
+import javax.swing.text.html.Option;
```
Comment (Skullians) [inline src/main/java/me/clip/placeholderapi/expansion/manager/LocalExpansionManager.java]: Unused import here

Comment (Skullians) [reply src/main/java/me/clip/placeholderapi/expansion/manager/LocalExpansionManager.java]: damn it you beat me to it

**Review by Skullians — APPROVED** [review]

**Review by BlitzOffline — APPROVED** [review]

**Review by NaysKutzu — APPROVED** [review]
I Approve
