### PR TITLE
Fix contract violations & add null checks which should close #515

### LINKED ISSUE #515: Error when registering expansions
### Issue
Expansions are not successfully registered after downloading using `papi ecloud download <expansion>`.

### Expected behaviour
PAPI should download, prompt to reload, and register the expansion after reloading.

### Actual behaviour
PAPI downloads the expansion, prompts to reload, but throws null pointer exceptions when reloading.
https://paste.helpch.at/redubilofa.bash

### How to reproduce

1. Download expansion using `papi ecloud download server`
2. `Successfully downloaded expansion Server [2.4.0] to file: Expansion-server.jar
Make sure to type /papi reload to enable your new expansion!`
3. Reload using `papi reload`

### `/papi dump` output
When I've been downloading expansions all names have been "Expansion-[lowercase plugin name]". Reloading PAPI does not register the newly downloaded expansions automatically. After looking at other issues and dumps, I realized that my expansion for server was called "Expansion-server.jar" in my dump, but "Expansion-Server.jar" in another user's dump. I redownloaded server from the ecloud and console still reported
`Successfully downloaded expansion Server [2.4.0] to file: Expansion-server.jar
Make sure to type /papi reload to enable your new expansion!`
First Dump https://paste.helpch.at/obapozepuf
After renaming the downloaded file to "Expansion-Server.jar" and then reloading PAPI, the expansion was successfully registered and recorded in a subsequent dump. https://paste.helpch.at/wesawaseto

Is there a list of the names or syntax PAPI looks for? `papi ecloud list all`? Some don't register using their ecloud name either. Example: "mcMMO" as seen in `papi ecloud list all` isn't registered when named "Expansion-mcmmo.jar" or "Expansion-mcMMO.jar" but is registered when named "Expansion-McMMO.jar".
I cannot get ListPlayers and SpeedPerSec to register. All of the others I have renamed and were successfully registered.
https://paste.helpch.at/olopujunoy
If I remove ListPlayers and SpeedPerSec the above null pointer exception also disappears.
https://paste.helpch.at/ruhefidomo
I'd really like to be able to just download, reload, and move on to implementation. The plugin should get the placeholders for me without needing me to double check the files are named correctly.

### PR DESCRIPTION
**Pull request by PiggyPiglet**
### Type

- [x] Internal change (Doesn't affect end-user).
- [ ] External change (Does affect end-user).
- [ ] Wiki (Changes towards the [Wiki]).
- [ ] Other: __________ 

### Description

Closes #515 

[Wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki

### CODE REVIEW

File: src/main/java/me/clip/placeholderapi/expansion/manager/LocalExpansionManager.java [hunk 1]
```diff
@@ -335,7 +336,14 @@ private void unregisterAll() {
       @NotNull final File file) {
     return CompletableFuture.supplyAsync(() -> {
       try {
-        return FileUtil.findClass(file, PlaceholderExpansion.class);
+        final Class<? extends PlaceholderExpansion> expansionClass = FileUtil.findClass(file, PlaceholderExpansion.class);
+
+        if (expansionClass == null) {
+          plugin.getLogger().severe("Failed to load Expansion: " + file.getName() + ", as it does not have" +
+                  "an a class which extends PlaceholderExpansion.");
```
Comment (Andre601) [inline src/main/java/me/clip/placeholderapi/expansion/manager/LocalExpansionManager.java:343]: typo?
